### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by alaurenzi** [ADVRHumanoids/concert_nav2#1]
- [x] create a robot description publisher node to avoid the /tmp/modularbot.*rdf disaster
 - [x] keep empty world as default
 - [x]  remove hardcoded values in path planner yaml files
```yaml
./concert_navigation/concert_navigation/config/bt_navigator copy.yaml:    default_nav_to_pose_bt_xml: "/home/user/data/concert_nav2_ws/src/concert_navigation/behavior_tree/behavior.xml"
./concert_navigation/concert_navigation/config/bt_navigator copy.yaml:    default_nav_through_poses_bt_xml: "/home/user/data/concert_nav2_ws/src/concert_navigation/behavior_tree/behavior.xml"
./concert_navigation/concert_navigation/config/bt_navigator copy 3.yaml:    default_nav_to_pose_bt_xml: "/home/user/data/concert_nav2_ws/src/concert_navigation/behavior_tree/behavior.xml"
./concert_navigation/concert_navigation/config/bt_navigator copy 3.yaml:    default_nav_through_poses_bt_xml: "/home/user/data/concert_nav2_ws/src/concert_navigation/behavior_tree/behavior.xml"
./concert_navigation/concert_navigation/config/bt_navigator copy 2.yaml:    default_nav_to_pose_bt_xml: "/home/user/data/concert_nav2_ws/src/concert_navigation/behavior_tree/behavior.xml"
./concert_navigation/concert_navigation/config/bt_navigator copy 2.yaml:    default_nav_through_poses_bt_xml: "/home/user/data/concert_nav2_ws/src/concert_navigation/behavior_tree/behavior.xml"
./concert_navigation/concert_navigation/config/bt_navigator.yaml:    default_nav_to_pose_bt_xml: "/home/user/data/concert_nav2_ws/src/concert_navigation/behavior_tree/behavior.xml"
./concert_navigation/concert_navigation/config/bt_navigator.yaml:    default_nav_through_poses_bt_xml: "/home/user/data/concert_nav2_ws/src/concert_navigation/behavior_tree/behavior.xml"
```
- [ ] ...
